SHELL := /bin/sh
CC    := gcc
CFLAGS := -Wall
TARGET1 := spidevtest
TARGET2 := MFRC522
all: $(TARGET1) $(TARGET2)
	
$(TARGET1): $(TARGET1).c
	$(CC) $(CFLAGS) -o $(TARGET1) $(TARGET1).c
$(TARGET2): $(TARGET2.c
	$(CC) $(CFLAGS) -o $(TARGET2) $(TARGET2).c
clean:
	-rm $(TARGET1)
	-rm $(TARGET2)